spring.application.name=spring-boot-webflux-apirest

# Configuracion de la base de datos MongoDB
# si no existe la bd, se crea automaticamente
spring.data.mongodb.uri=mongodb://localhost:27017/springboot-webflux